common:
  service_log: "" # log file path  /data/logs/mybinary.log  if not set , log output to stdout  
  log_level: "debug" #
  pid_file: "/data/logs/my.pid"

http:
  serviceid: "myservice"
  http_addr: "0.0.0.0:7788"
  pprof_addr: "127.0.0.1:7489"
  http_timeout: 30

mysql:
  datasource: "dbuser:xxxxxxxx@tcp(10.101.255.255:39999)/mydbc?parseTime=true&loc=Local&charset=utf8"
  max_open_conn: 50
  max_idle_conn: 10
  # uint: min
  max_conn_lifetime: 0
  max_conn_idletime: 0

tpaas:
  urls:
  - "http://172.27.139.93:8090"
  - "http://172.27.139.93:8090"

