common:
  service_log: "/data/logs/api.log"
  access_log: "/data/logs/access.log"
  tracer_log: "/data/logs/tracing.log"
  log_level: "debug" #
  pid_file: "/data/logs/tpaasportal.pid"

http:
  serviceid: "myservice"
  http_addr: "0.0.0.0:8088"
  pprof_addr: "127.0.0.1:6489"
  http_timeout: 30

mysql:
  datasource: "dbuser:xxxxxxxx@tcp(10.101.255.255:39999)/mydbc?parseTime=true&loc=Local&charset=utf8"
  maxconn: 100

